mode = "fastest"

[light_sources]
	water_sensitive_check = false
	block_entities = false
	entities = false
	self = true
	tnt = "simple"
	creeper = "simple"
	beam = true
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				player = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				arrow = true
				axolotl = true
				bat = true
				bee = true
				blaze = true
				block_display = true
				boat = true
				chest_boat = true
				camel = true
				cat = true
				cave_spider = true
				chicken = true
				cod = true
				cow = true
				creeper = true
				dolphin = true
				donkey = true
				dragon_fireball = true
				drowned = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				enderman = true
				endermite = true
				evoker = true
				evoker_fangs = true
				experience_orb = true
				eye_of_ender = true
				falling_block = true
				fireball = true
				firework_rocket = true
				fishing_bobber = true
				fox = true
				frog = true
				ghast = true
				giant = true
				glow_item_frame = true
				glow_squid = true
				goat = true
				guardian = true
				hoglin = true
				horse = true
				husk = true
				illusioner = true
				interaction = true
				iron_golem = true
				item = true
				item_display = true
				item_frame = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				chest_minecart = true
				command_block_minecart = true
				furnace_minecart = true
				hopper_minecart = true
				spawner_minecart = true
				tnt_minecart = true
				mooshroom = true
				mule = true
				ocelot = true
				painting = true
				panda = true
				parrot = true
				phantom = true
				pig = true
				piglin = true
				piglin_brute = true
				pillager = true
				polar_bear = true
				potion = true
				tnt = true
				pufferfish = true
				rabbit = true
				ravager = true
				salmon = true
				sheep = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton = true
				skeleton_horse = true
				slime = true
				small_fireball = true
				sniffer = true
				snow_golem = true
				snowball = true
				spectral_arrow = true
				spider = true
				squid = true
				stray = true
				strider = true
				tadpole = true
				text_display = true
				experience_bottle = true
				egg = true
				ender_pearl = true
				trader_llama = true
				trident = true
				tropical_fish = true
				turtle = true
				vex = true
				villager = true
				vindicator = true
				wandering_trader = true
				warden = true
				witch = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				wolf = true
				zoglin = true
				zombie = true
				zombie_horse = true
				zombie_villager = true
				zombified_piglin = true

			[light_sources.settings.entities.mtr]
				rendering = true

			[light_sources.settings.entities.easy_npc]
				allay = true
				cat = true
				chicken = true
				drowned = true
				evoker = true
				fairy = true
				horse = true
				humanoid = true
				humanoid_slim = true
				husk = true
				illusioner = true
				iron_golem = true
				orc = true
				orc_warrior = true
				pig = true
				piglin = true
				piglin_brute = true
				pillager = true
				skeleton = true
				skeleton_horse = true
				stray = true
				villager = true
				vindicator = true
				wither_skeleton = true
				wolf = true
				zombie = true
				zombie_horse = true
				zombie_villager = true
				piglin_zombified = true
				piglin_raw = true
				skeleton_raw = true
				zombie_raw = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.regen]
				cyber_master = true
				timelord = true
				watcher = true
				laser = true

			[light_sources.settings.entities.immersive_paintings]
				glow_graffiti = true
				glow_painting = true
				graffiti = true
				painting = true

			[light_sources.settings.entities.tacz]
				target_minecart = true
				bullet = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.mcwfurnitures]
				chair_entity = true

			[light_sources.settings.entities.refurbished_furniture]
				seat = true

			[light_sources.settings.entities.tjmetro]
				seat = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false
