version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
mcwdoors = true
mtr = true
fastitemframes = true
mcwfences = true
mcwroofs = true
londonunderground = true
create = true
mcwwindows = true
jsblock = true
templates = true
lockandblock = true
placeable_food = true
redstonepen = true
mcwstairs = true
another_furniture = true
refurbished_furniture = true
trafficcraft = true
automobility = true
gravity_changer = true
minecraft = true
msd = true
dramaticdoors = true
diagonalwalls = true
slide_show = true
railways = true
mcwfurnitures = true
tjmetro = true
mcwbridges = true
aether = true
concreteslabsandstairs = true
mcwtrpdoors = true
easy_npc = true
milk = true
dragonlib = true
diagonalwindows = true
tacz = true
bedrockify = true
diagonalfences = true
mtrsteamloco = true
waterframes = true
