
#Client
[client]
	#Toggle whether the mod downloads it's own pack of Doctor who Skins
	downloadInternalSkins = true
	#Disabling this will disable skin changing for you and you will retain your Mojang one
	changeMySkin = true
	#Toggle whether a bunch of trending skins are downloaded from mineskin
	downloadTrendingSkins = false
	#Changes the players perspective on regeneration
	changePerspective = true
	#Toggle whether Timelords second head layers render, as some look good without and some look good with, I just leave this decision up to you
	timelordRenderSecondLayers = true

